### ISSUE TITLE
Failing builds in CI

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#1440]
Currently CI is failing, due to two issues it seems in Ember:
* ~https://github.com/emberjs/ember.js/issues/19408~
* ~https://github.com/emberjs/ember.js/issues/19431~
* ~https://github.com/embroider-build/embroider/issues/701~
* Failing tests due to raised deprecations
  * ~deprecations in canary due to missing `this.` in some templates, makes the tests fail~
  * ~Expected no deprecations, found: "Versions of modifier manager capabilities prior to 3.22 have been deprecated. You must update to the 3.22 capabilities."~
  * Invoking the `<LinkTo>` component with positional arguments is deprecated. WIP: #1455 
  * `Usage of the Ember Global is deprecated.`

Posting here for visibility

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/issues/19408 should have been fixed on canary already in https://github.com/emberjs/ember.js/pull/19395, please confirm?


https://github.com/emberjs/ember.js/issues/19431 is fixed by https://github.com/ember-cli/ember-cli-htmlbars/releases/tag/v5.6.0.

**Comment by simonihmig** [comment]
> emberjs/ember.js#19408 should have been fixed on canary already in emberjs/ember.js#19395, please confirm?

@rwjblue yes, does not happen in canary anymore, but still see it in ember-release.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/issues/19408 should be fixed (released in 3.24.3 and 3.25.3).

**Comment by simonihmig** [comment]
Closed by #1477
